//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADB.SA.Reports.Presenter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADB.SA.Reports.Presenter.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagrams.
        /// </summary>
        internal static string DiagramsFolder {
            get {
                return ResourceManager.GetString("DiagramsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/div&gt;.
        /// </summary>
        internal static string DivEndTag {
            get {
                return ResourceManager.GetString("DivEndTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;{0}&quot;&gt;.
        /// </summary>
        internal static string DivWithClassPropertyFormat {
            get {
                return ResourceManager.GetString("DivWithClassPropertyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {split}.
        /// </summary>
        internal static string Split {
            get {
                return ResourceManager.GetString("Split", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td class={0}&gt;{1}&lt;/td&gt;.
        /// </summary>
        internal static string TableCell {
            get {
                return ResourceManager.GetString("TableCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td class={0}&gt;{1}:&lt;/td&gt;.
        /// </summary>
        internal static string TableCellLabel {
            get {
                return ResourceManager.GetString("TableCellLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td class=&quot;{0}&quot; colspan=&quot;{1}&quot;&gt;{2}&lt;/td&gt;.
        /// </summary>
        internal static string TableCellWithColSpan {
            get {
                return ResourceManager.GetString("TableCellWithColSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td class=&quot;{0}&quot; rowspan=&quot;{1}&quot;&gt;{2}&lt;/td&gt;.
        /// </summary>
        internal static string TableCellWithRowSpan {
            get {
                return ResourceManager.GetString("TableCellWithRowSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/table&gt;.
        /// </summary>
        internal static string TableEndTag {
            get {
                return ResourceManager.GetString("TableEndTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;th colspan={0}&gt;{1}&lt;/th&gt;.
        /// </summary>
        internal static string TableHeaderTag {
            get {
                return ResourceManager.GetString("TableHeaderTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td style={0}&gt;{1}&lt;/td&gt;.
        /// </summary>
        internal static string TableReportCell {
            get {
                return ResourceManager.GetString("TableReportCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table cellspacing=0 cellpadding=0 border=1 style={0} width=100%&gt;.
        /// </summary>
        internal static string TableReportStartTag {
            get {
                return ResourceManager.GetString("TableReportStartTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/tr&gt;.
        /// </summary>
        internal static string TableRowEndTag {
            get {
                return ResourceManager.GetString("TableRowEndTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;.
        /// </summary>
        internal static string TableRowStartTag {
            get {
                return ResourceManager.GetString("TableRowStartTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table cellspacing=0 border=0 class={0} width=100%&gt;.
        /// </summary>
        internal static string TableStartTag {
            get {
                return ResourceManager.GetString("TableStartTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/ul&gt;.
        /// </summary>
        internal static string UlEndTag {
            get {
                return ResourceManager.GetString("UlEndTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;.
        /// </summary>
        internal static string UlStartTag {
            get {
                return ResourceManager.GetString("UlStartTag", resourceCulture);
            }
        }
    }
}
